### ISSUE TITLE
Can't Restore

### ISSUE THREAD

**Issue by Silvenga** [docker-infra/docker-backup#11]
When I try to restore I get the following:
```
./docker-backup restore backup
2014/11/02 18:34:52 Restoring backup
2014/11/02 18:34:53 HTTP Internal Server Error: Content-Type specified () must be 'application/json'
```
I'm using Docker 1.3.1. Is there any way to get more information?

**Comment by boombatower** [comment]
:+1:

**Comment by discordianfish** [comment]
I think this is fixed by https://github.com/docker-infra/docker-backup/commit/0d743eb24cb20f25af366c735499f49db94b3d5b

**Comment by discordianfish** [comment]
Assuming this is fixed. Let me know if not.

**Comment by Silvenga** [comment]
@discordianfish Sorry, must have missed the emails. Unfortunately, I've moved to a different backup implementation so I can't test. Thanks though!
