### ISSUE TITLE
There is no image fish/docker-backup on the docker hub

### ISSUE THREAD

**Issue by noisy** [docker-infra/docker-backup#12]
There is another repository [docker-lloyd](https://github.com/discordianfish/docker-lloyd) containing a reference to `fish/docker-backup` image. Currently thete is no such image, so every user have to fork and create own image.

@discordianfish: Could you recreate this image?

**Comment by discordianfish** [comment]
Hi @noisy,

sorry for the confusion and thanks for spotting this.
There was some shuffling around going on. I move things from my private github account to the docker-infra account and missed the docker-backup image.
That's fixed now: Just make sure you use the `dckr` images, so `dckr/docker-lloyd` or `dckr/docker-backup`. (the lloyd image now referes to the dckr/docker-backup image as well).

Let me know if things are working for you now!
