### ISSUE TITLE
Alternative?

### ISSUE THREAD

**Issue by benpye** [docker-infra/docker-backup#22]
Now this is no longer being maintained are there any recommended alternatives to this? I haven't found anything comparable as of yet but I'd like to be proven wrong.

**Comment by grahovam** [comment]
I didn't find anything, too. That's why i build this: 
https://github.com/grahovam/docker-backup-gpg-s3
It takes a volume, compresses it, encrypts it and sends it to S3.

**Comment by discordianfish** [comment]
@xbglowx Didn't you want to close/make private this repo? Then people would get redirected to my fork: https://github.com/discordianfish/docker-backup

**Comment by xbglowx** [comment]
@discordianfish I was going to keep it public, since I noticed many stars. But, since you are actively maintaining your repo, I will make this private. Thanks!

@benpye @grahovam please us https://github.com/discordianfish/docker-backup.
